# Generated by Django 4.2.3 on 2023-10-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.BigIntegerField()),
                ('fname', models.CharField()),
                ('fphone', models.BigIntegerField()),
                ('fnumber', models.BigIntegerField(max_length=2)),
            ],
        ),
    ]
