# Generated by Django 4.2.3 on 2023-11-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
