# Generated by Django 4.2.3 on 2023-11-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_flogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='flogin',
            name='firstname',
            field=models.CharField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flogin',
            name='lastname',
            field=models.CharField(default='0'),
            preserve_default=False,
        ),
    ]
